CREATE TABLE review(
user_id INTEGER NOT NULL,
product_id INTEGER NOT NULL,
post_date DATE NOT NULL,
review_rate DOUBLE NOT NULL,
review_contents VARCHAR(400) NOT NULL,
PRIMARY KEY (user_id,product_id),
FOREIGN KEY (user_id) REFERENCES user(user_id),
FOREIGN KEY (product_id) REFERENCES product(product_id)
);

INSERT INTO review values(1,1,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,1,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,1,CURRENT_DATE(),1,"レビューの内容：********************"),
(1,2,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,2,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,2,CURRENT_DATE(),1,"レビューの内容：********************"),
(1,3,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,3,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,3,CURRENT_DATE(),1,"レビューの内容：********************"),
(1,4,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,4,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,4,CURRENT_DATE(),1,"レビューの内容：********************"),
(1,5,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,5,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,5,CURRENT_DATE(),1,"レビューの内容：********************"),
(1,6,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,6,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,6,CURRENT_DATE(),1,"レビューの内容：********************"),
(1,7,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,7,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,7,CURRENT_DATE(),1,"レビューの内容：********************"),
(1,8,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,8,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,8,CURRENT_DATE(),1,"レビューの内容：********************"),
(1,9,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,9,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,9,CURRENT_DATE(),1,"レビューの内容：********************"),
(1,10,CURRENT_DATE(),1,"レビューの内容：********************"),
(2,10,CURRENT_DATE(),1,"レビューの内容：********************"),
(3,10,CURRENT_DATE(),1,"レビューの内容：********************");